# Generated by Django 3.1.5 on 2021-01-14 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'ordering': ('created_datetime',),
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='내용')),
                ('is_important', models.BooleanField(choices=[(True, '중요'), (False, '중요하지 않음')], default=False, verbose_name='중요도설정')),
                ('is_checked', models.BooleanField(choices=[(True, '완료'), (False, '완료되지 않음')], default=False, verbose_name='할일완료')),
                ('to_do_date_time', models.DateTimeField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('to_do_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_do', to='to_do.todolist')),
            ],
            options={
                'ordering': ('-is_important', '-to_do_date_time', '-created_datetime'),
            },
        ),
    ]
